# Generated by Django 5.2.8 on 2025-11-26 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_iata', models.CharField(max_length=3, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aerolínea',
                'verbose_name_plural': 'Aerolíneas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('fabricante', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avión',
                'verbose_name_plural': 'Aviones',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=20, unique=True)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('Activo', 'Activo'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vuelos', to='vuelos.aerolinea')),
                ('avion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuelos', to='vuelos.avion')),
            ],
            options={
                'verbose_name': 'Vuelo',
                'verbose_name_plural': 'Vuelos',
                'ordering': ['fecha_salida', 'hora_salida', 'numero_vuelo'],
            },
        ),
    ]
